### ISSUE TITLE
Pluto is not a planet!

### ISSUE THREAD

**Issue by c-martinez** [mkuzak/colonize#1]
@mkuzak , with all due respect... YOU ARE WRONG! pluto is not a planet.

**Comment by mkuzak** [comment]
Sure, but I'd prefer you do it yourself, do you want to collaborate on that?

**Comment by c-martinez** [comment]
Sure!

**Comment by c-martinez** [comment]
Please make me a contributor!

**Comment by c-martinez** [comment]
Done fixed by latest commit.
